apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 3

  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: switchover

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "1GB"
      effective_cache_size: "3GB"
      maintenance_work_mem: "256MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "4MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"

    pg_hba:
      - host all all all scram-sha-256

  bootstrap:
    initdb:
      database: planet
      owner: planet
      secret:
        name: postgres-app

  superuserSecret:
    name: postgres-superuser

  storage:
    size: 200Gi
    storageClass: oci-bv

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: oci-object-storage

  managed:
    roles:
      - name: planet
        ensure: present
        login: true
        replication: true
        connectionLimit: -1
        inRoles:
          - pg_monitor

  resources:
    requests:
      memory: "4Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "1000m"
